### PR TITLE
Make Directories Dynamically

### PR DESCRIPTION
**Pull request by ArtSabintsev**
Instead of throwing an error if a directory doesn't exist, the script now generates directories dynamically.

Just a rough/dirty implementation for now.

### CODE REVIEW

**Comment by ArtSabintsev** [comment]
I'll fix the merge conflict soon.

**Comment by ArtSabintsev** [comment]
Alright, this is ready for review. Again, this is a quick and dirty implementation to prove out the concept. 

Also, you may want to merge #12 before looking at this one.

**Comment by JohnSundell** [comment]
@ArtSabintsev It looks like with this implementation, an extra directory will be created. So if specify `/users/john/project/` as my destination and then `MyProject` and the name, the path will be `/users/john/project/MyProject/`. Is that right?

**Comment by ArtSabintsev** [comment]
Ya, good point. Not sure what I was thinking. Going to nuke this PR. Thanks.

**Comment by JohnSundell** [comment]
No problems! 👍

**Pull request closed without merging**
